### ISSUE TITLE
Regarding compliance with license terms

### ISSUE THREAD

**Issue by voluntas** [GetStream/webrtc#27]
Please be advised that all patches distributed through https://github.com/shiguredo-webrtc-build/webrtc-build/ are licensed under the Apache License 2.0.

If you wish to continue using these patches, please ensure compliance with the license terms.

**Comment by kanat** [comment]
Hi @voluntas,

Thanks for bringing this into the spotlight 👍 
We'll address this asap.

**Comment by kanat** [comment]
Hi @voluntas,

Sorry for the delay in addressing this. Thanks for your patience and for highlighting the issue.
